;;(setq w3m-icon-directory "/usr/share/emacs/22.3/etc/images/w3m/")
(setq w3m-use-cookies t)
(setq w3m-keep-arrived-urls 0)
(setq w3m-show-graphic-icons-in-mode-line t)
(setq w3m-show-graphic-icons-in-header-line t)
(setq w3m-use-toolbar t)
(autoload 'w3m "w3m" "Interface for w3m on Emacs." t)
(autoload 'w3m-browse-url "w3m" "Ask a WWW browser to show a URL." t)
(autoload 'w3m-find-file "w3m" "Find a local file using emacs-w3m." t)
(autoload 'w3m-search "w3m-search" "Search words using emacs-w3m." t)
(autoload 'w3m-weather "w3m-weather" "Display a weather report." t)
(autoload 'w3m-antenna "w3m-antenna" "Report changes of web sites." t)
(autoload 'w3m-namazu "w3m-namazu" "Search files with Namazu." t)
