* Каналы связи
** Нужно создать библиотеку реализующую интерфейс взаимодействия с процессами каналов связи из сторонних процессов  (от одной до двух недель)
** Сделать  настраиваемым в config.h.in размер snap пакета. (от одного до трех дней)
** Необходимо реализовать подстановку адресов источника и назначения из данных команды CMD_COMMUNCH_SEND _EXTENDED в snap пакет. Сейчас адреса берутся только из конфигурационного файла. (от одного   до четырех дней)

* Канал связи глобастар (вообще он нужен?) 
  Необходимы доработки модуля, первичное тестирование. (от двух недель до двух месяцев) 
  
* Каналы связи tcp/ip соединением  
** Проверить отправку пакета пинга сразу после установки ip соединения .  (1 день)  

* Канал связи gprs
** Поддержка  в  канале связи gprs, модема для Системы контроля уровня воды в водохранилище -  "Варяг".Возможно реализовать, когда появится сам модем.  (от 1 недели - до месяца)

** Поддержка в  канале связи gprs ,модема для новых плат мобиса  (на процессоре   imx). Возможно реализовать, когда появится доступ к плате с модемом.  (от 1 недели - до двух месяцев)

** Поддержка приёма и отправки SMS в новой плате мобиса (на процессоре imx). (от 1 недели - до месяца)

** Выделить в отдельный модуль установки ppp соединения , и модуль установки ip соединения сделать единым с communch-ip. (от 1 недели - до месяца)

* Канал связи ip
** Поддержка маршрутизации по источнику, с автоопределением адреса источника по интерфейсу. (от 1 недели - до 2-х недель)


* Загрузчик файлов для медиаплеера
  Доработка модуля, написание тестов (от двух недель до полутора месяцев)
