* БСИ и КУГО
  
** DONE Электросчетчик проверка ввода параметров и пересчет при изменении.
   CLOSED: [2017-12-25 Пн 15:18]
** DONE Сделать dmr канал как обычный канал.(остановка таймера ожидания запроса вне оповещения)
   CLOSED: [2017-12-25 Пн 15:18]
** DONE Ввести в очередь приоритет для отправки результатов оповещения  
   CLOSED: [2018-04-06 Пт 09:54]
** DONE Сделать блокировку отправки всяких там левых квитанций на время оповещения  
   CLOSED: [2018-04-06 Пт 10:19]
*** DONE Разруливается и приоритетами сообщения     
    CLOSED: [2018-04-06 Пт 10:20]
** DONE Вебинтерфейс для прошивки модема(не нужен так как будем исключать модем).
   CLOSED: [2018-06-04 Пн 14:56]
** DONE Доработка протокола общения с модемом dmr. 
    CLOSED: [2018-06-04 Пн 14:59]
**** DONE Версии модема выдачу
     CLOSED: [2018-06-04 Пн 14:59]
**** DONE Состояние дискредного входа радиостанции PTT  по запросу
     CLOSED: [2018-06-04 Пн 14:59]
** ______________ Дела Архивные: _______________
*** Очередь отправки для даннных с датчиков , как сделать чтобы не накапливались? 
*** Частично Разруливается ограничением размера очереди, и приоритетами сообщения    
*** + Надо вытягивать при сборе только текущее значение датчика  *
*** Расписать тайминги ??? (о чем это?)
*** Анализ отпадения радиостанции ???
*** Тестирование системы с оболочки вручную + оставляем на несколько дней в работе, в режиме опроса. 
**** Выводить strace логе ID пакета. 
**** РАСПИСАТЬ как будем тестировать непосредственно ооавещение
*** Размер звука не правильный выдается вроде как, наверх. 
*** qtrace выводим адрес абонента
*** strace выводим код сессии
** ______________ Дела Текущие: _______________
*** Доработка проекта alarm-kugo под интерфейс драйвера радиостанции Hytera
**** Уведомление о приеме пакетов звуковых (интерфейс)
**** communch-radio-ax25:                  
***** функции приема/передачи пакетов (интерфейс)
**** alarm-bsi:
***** функции включения PTT, получения подтверждения от драйвера о переключении PTT  (интерфейс)
*** Тестирование проекта alarm-kugo под интерфейс драйвера радиостанции Hytera
**** Добавить в систему syslog-ng, rsyslog, для сведения логов, по сети, в одну точку.
*** Доработка системы логирования проекта alarm-kugo.
**** Cделать  уровень логов ??? уровни(LOG_INFO,LOG_DEBUG ... )
**** Формат полей вывода в лог.
**** Имя группы сообщений. (можно выводить в лог по этому параметру)
**** Автоматическое имя модуля =  "имя класса+имя функции" 
**** Переключение уровня логов на лету. 
    

