* БСИ и КУГО
  
** DONE Электросчетчик проверка ввода параметров и пересчет при изменении.
   CLOSED: [2017-12-25 Пн 15:18]
** DONE Сделать dmr канал как обычный канал.(остановка таймера ожидания запроса вне оповещения)
   CLOSED: [2017-12-25 Пн 15:18]
** DONE Ввести в очередь приоритет для отправки результатов оповещения  
   CLOSED: [2018-04-06 Пт 09:54]
** DONE Сделать блокировку отправки всяких там левых квитанций на время оповещения  
   CLOSED: [2018-04-06 Пт 10:19]
*** DONE Разруливается и приоритетами сообщения     
    CLOSED: [2018-04-06 Пт 10:20]
** Вебинтерфейс для прошивки модема.
** Очередь отправки для даннных с датчиков , как сделать чтобы не накапливались? 
*** Частично Разруливается ограничением размера очереди, и приоритетами сообщения    
*** + Надо вытягивать при сборе только текущее значение датчика  *
** Расписать тайминги ??? (о чем это?)
** Анализ отпадения радиостанции
** ______________ Текущие дела: _______________
*** Доработка протокола общения с модемом dmr. 
**** Версии модема выдачу
**** Состояние дискредного входа радиостанции PTT  по запросу
*** Тестирование системы с оболочки вручную + оставляем на несколько дней в работе, в режиме опроса. 
**** Выводить strace логе ID пакета. 
**** РАСПИСАТЬ как будем тестировать непосредственно ооавещение
*** Размер звука не правильный выдается вроде как, наверх. 
*** qtrace выводим адрес абонента
*** strace выводим код сессии

